/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoiTac;

import MainPage.DatabaseConnection;
import static MainPage.MainLogin.getAccountID;
import static MainPage.MainLogin.getDBConnection;
import static MainPage.MainRegister.getPassword;
import static MainPage.MainRegister.getUsername;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.CallableStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */


public class MainPartnerForm extends javax.swing.JFrame {
    public void ReFresh(){
        tableProduct = (DefaultTableModel)jTableProduct.getModel();
        tableProduct.setRowCount(0);
        String queryProduct = "SELECT * FROM DTV_DTSANPHAM";
        try{
            PreparedStatement ppState = _connection.prepareStatement(queryProduct);
            rs = ppState.executeQuery();
            while(rs.next()){
                tableProduct.addRow(new Object[]{rs.getString("MASP"),
                rs.getString("TENSP"),rs.getInt("DONGIA")});
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ProductPane, "SYS ERROR!!");
        }
    }
    
    ResultSet rs = null;
    DefaultTableModel tableOrder;
    DefaultTableModel tableContract;
    DefaultTableModel tableBranch;
    DefaultTableModel tableProduct;
    private static Connection _connection;
    private static String partnerID;
    DatabaseConnection db;
    public void switchPanels(JPanel panel){
        layeredPane.removeAll();
        layeredPane.add(panel);
        layeredPane.repaint();
        layeredPane.revalidate();
    }
    
    public static String getPartnerID(){
        return partnerID;
    }
    public static Connection getConnection(){
        return _connection;
    }
    /**
     * Creates new form CreateContractForm
     */
    public MainPartnerForm() {
        db = new DatabaseConnection();
        partnerID = getAccountID();
        _connection = getDBConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        AccountButton = new javax.swing.JButton();
        AccountButton1 = new javax.swing.JButton();
        BranchNavButton = new javax.swing.JButton();
        ContractNavButton = new javax.swing.JButton();
        ProductNavButton = new javax.swing.JButton();
        layeredPane = new javax.swing.JLayeredPane();
        ContractPane = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContract = new javax.swing.JTable();
        WatchDetailContractButton = new javax.swing.JButton();
        ProductPane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        DeleteProductButton = new javax.swing.JButton();
        inPriceFixButton = new javax.swing.JButton();
        BranchSupButton = new javax.swing.JButton();
        CutPriceDLProductButton = new javax.swing.JButton();
        inPriceButton = new javax.swing.JButton();
        CutPriceProductButton = new javax.swing.JButton();
        AmountTextField = new javax.swing.JTextField();
        inPriceDLButton = new javax.swing.JButton();
        BranchPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBranch = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        OrderPane = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        UpdateOrderButton = new javax.swing.JButton();
        OrderNavButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 222, 105));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/266707509_438798897746812_6825311753133148119_n.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AccountButton.setText("Account");
        AccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountButtonActionPerformed(evt);
            }
        });

        AccountButton1.setText("Exit");
        AccountButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountButton1ActionPerformed(evt);
            }
        });

        BranchNavButton.setBackground(new java.awt.Color(190, 8, 8));
        BranchNavButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BranchNavButton.setForeground(new java.awt.Color(255, 255, 255));
        BranchNavButton.setText("Branch");
        BranchNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchNavButtonActionPerformed(evt);
            }
        });

        ContractNavButton.setBackground(new java.awt.Color(190, 8, 8));
        ContractNavButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ContractNavButton.setForeground(new java.awt.Color(255, 255, 255));
        ContractNavButton.setText("Contract");
        ContractNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContractNavButtonActionPerformed(evt);
            }
        });

        ProductNavButton.setBackground(new java.awt.Color(190, 8, 8));
        ProductNavButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductNavButton.setForeground(new java.awt.Color(255, 255, 255));
        ProductNavButton.setText("Product");
        ProductNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNavButtonActionPerformed(evt);
            }
        });

        layeredPane.setLayout(new java.awt.CardLayout());

        ContractPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(190, 8, 8));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contract List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 60, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTableContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ContractID", "PartnerID", "Branch quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableContract.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTableContract);

        WatchDetailContractButton.setText("Watch Detail");
        WatchDetailContractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatchDetailContractButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContractPaneLayout = new javax.swing.GroupLayout(ContractPane);
        ContractPane.setLayout(ContractPaneLayout);
        ContractPaneLayout.setHorizontalGroup(
            ContractPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractPaneLayout.createSequentialGroup()
                .addGroup(ContractPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WatchDetailContractButton)
                    .addGroup(ContractPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContractPaneLayout.createSequentialGroup()
                            .addGap(263, 263, 263)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContractPaneLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ContractPaneLayout.setVerticalGroup(
            ContractPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WatchDetailContractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layeredPane.add(ContractPane, "card3");

        jPanel2.setBackground(new java.awt.Color(190, 8, 8));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 80, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 81, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        AddProductButton.setBackground(new java.awt.Color(190, 8, 8));
        AddProductButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddProductButton.setForeground(new java.awt.Color(255, 255, 255));
        AddProductButton.setText("Add");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product name", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProduct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableProduct);

        DeleteProductButton.setBackground(new java.awt.Color(190, 8, 8));
        DeleteProductButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteProductButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteProductButton.setText("Delete");
        DeleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductButtonActionPerformed(evt);
            }
        });

        inPriceFixButton.setBackground(new java.awt.Color(190, 8, 8));
        inPriceFixButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inPriceFixButton.setForeground(new java.awt.Color(255, 255, 255));
        inPriceFixButton.setText("Increase(fix)");
        inPriceFixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPriceFixButtonActionPerformed(evt);
            }
        });

        BranchSupButton.setBackground(new java.awt.Color(190, 8, 8));
        BranchSupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BranchSupButton.setForeground(new java.awt.Color(255, 255, 255));
        BranchSupButton.setText("Branch supply");
        BranchSupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchSupButtonActionPerformed(evt);
            }
        });

        CutPriceDLProductButton.setBackground(new java.awt.Color(190, 8, 8));
        CutPriceDLProductButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CutPriceDLProductButton.setForeground(new java.awt.Color(255, 255, 255));
        CutPriceDLProductButton.setText("Cut-DL");
        CutPriceDLProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutPriceDLProductButtonActionPerformed(evt);
            }
        });

        inPriceButton.setBackground(new java.awt.Color(190, 8, 8));
        inPriceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inPriceButton.setForeground(new java.awt.Color(255, 255, 255));
        inPriceButton.setText("Increase");
        inPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPriceButtonActionPerformed(evt);
            }
        });

        CutPriceProductButton.setBackground(new java.awt.Color(190, 8, 8));
        CutPriceProductButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CutPriceProductButton.setForeground(new java.awt.Color(255, 255, 255));
        CutPriceProductButton.setText("Cut-price");
        CutPriceProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutPriceProductButtonActionPerformed(evt);
            }
        });

        AmountTextField.setText("Amount:");

        inPriceDLButton.setBackground(new java.awt.Color(190, 8, 8));
        inPriceDLButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inPriceDLButton.setForeground(new java.awt.Color(255, 255, 255));
        inPriceDLButton.setText("Increase-DL");
        inPriceDLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPriceDLButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPaneLayout = new javax.swing.GroupLayout(ProductPane);
        ProductPane.setLayout(ProductPaneLayout);
        ProductPaneLayout.setHorizontalGroup(
            ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPaneLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPaneLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPaneLayout.createSequentialGroup()
                        .addComponent(BranchSupButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPaneLayout.createSequentialGroup()
                                .addComponent(AmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPaneLayout.createSequentialGroup()
                                .addComponent(CutPriceProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inPriceFixButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CutPriceDLProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(inPriceDLButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        ProductPaneLayout.setVerticalGroup(
            ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProductButton)
                    .addComponent(DeleteProductButton)
                    .addComponent(BranchSupButton)
                    .addComponent(inPriceButton)
                    .addComponent(AmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inPriceDLButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CutPriceDLProductButton)
                    .addComponent(CutPriceProductButton)
                    .addComponent(inPriceFixButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        layeredPane.add(ProductPane, "card2");

        BranchPane.setBackground(new java.awt.Color(255, 255, 255));

        jTableBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BranchID", "ContractID", "Address", "Number of Orders"
            }
        ));
        jScrollPane3.setViewportView(jTableBranch);

        jPanel4.setBackground(new java.awt.Color(190, 8, 8));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BRANCH LIST");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout BranchPaneLayout = new javax.swing.GroupLayout(BranchPane);
        BranchPane.setLayout(BranchPaneLayout);
        BranchPaneLayout.setHorizontalGroup(
            BranchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BranchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BranchPaneLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BranchPaneLayout.setVerticalGroup(
            BranchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BranchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layeredPane.add(BranchPane, "card4");

        OrderPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(190, 8, 8));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ORDER LIST");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "ProductID", "Quantity", "UnitPrice", "Total", "ShipAddress", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableOrder);

        UpdateOrderButton.setText("Update");
        UpdateOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderPaneLayout = new javax.swing.GroupLayout(OrderPane);
        OrderPane.setLayout(OrderPaneLayout);
        OrderPaneLayout.setHorizontalGroup(
            OrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPaneLayout.createSequentialGroup()
                        .addGap(0, 239, Short.MAX_VALUE)
                        .addGroup(OrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPaneLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPaneLayout.createSequentialGroup()
                                .addComponent(UpdateOrderButton)
                                .addContainerGap())))))
        );
        OrderPaneLayout.setVerticalGroup(
            OrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(UpdateOrderButton)
                .addContainerGap())
        );

        layeredPane.add(OrderPane, "card5");

        OrderNavButton.setBackground(new java.awt.Color(190, 8, 8));
        OrderNavButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OrderNavButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderNavButton.setText("Order");
        OrderNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderNavButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(43, 43, 43)
                        .addComponent(BranchNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ContractNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OrderNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(AccountButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BranchNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContractNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AccountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AccountButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        setSize(new java.awt.Dimension(816, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Faststore");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BranchNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchNavButtonActionPerformed
        switchPanels(BranchPane);
        tableBranch = (DefaultTableModel)jTableBranch.getModel();
        tableBranch.setRowCount(0);
        //String queryOrder = "SELECT * FROM CHINHANH";
        String queryOrder = "SELECT * FROM DTV_DTCHINHANH";
        try{
            PreparedStatement ppState = _connection.prepareStatement(queryOrder);
            rs = ppState.executeQuery();
            while(rs.next()){
                tableBranch.addRow(new Object[]{rs.getString("MACN"),
                rs.getString("MAHD"),rs.getString("DIACHICN"),rs.getInt("SODONHANG")});
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(BranchPane, "SYS ERROR!!");
        }     
    }//GEN-LAST:event_BranchNavButtonActionPerformed

    private void ContractNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContractNavButtonActionPerformed
        switchPanels(ContractPane);
        tableContract = (DefaultTableModel)jTableContract.getModel();
        tableContract.setRowCount(0);
        //String queryOrder = "SELECT * FROM HOPDONG";
        String queryOrder = "SELECT * FROM DTV_DTHOPDONG";
        
        try{
            PreparedStatement ppState = _connection.prepareStatement(queryOrder);
            rs = ppState.executeQuery();
            while(rs.next()){
                tableContract.addRow(new Object[]{rs.getString("MAHD"),
                rs.getString("MADT"),rs.getInt("SOCHINHANH")});
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ContractPane, "SYS ERROR!!");
        }        
    }//GEN-LAST:event_ContractNavButtonActionPerformed

    private void ProductNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNavButtonActionPerformed
        switchPanels(ProductPane);
        tableProduct = (DefaultTableModel)jTableProduct.getModel();
        tableProduct.setRowCount(0);
        String queryProduct = "SELECT * FROM DTV_DTSANPHAM";
        try{
            PreparedStatement ppState = _connection.prepareStatement(queryProduct);
            rs = ppState.executeQuery();            
            while(rs.next()){
                tableProduct.addRow(new Object[]{rs.getString("MASP"),
                rs.getString("TENSP"),rs.getInt("DONGIA")});
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ProductPane, "SYS ERROR!!");
        }
    }//GEN-LAST:event_ProductNavButtonActionPerformed

    private void OrderNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderNavButtonActionPerformed
        switchPanels(OrderPane);
        tableOrder = (DefaultTableModel)jTableOrder.getModel();
        tableOrder.setRowCount(0);
        String queryOrder = "SELECT * FROM DTV_DTDONHANG";
        try{
            PreparedStatement ppState = _connection.prepareStatement(queryOrder);
            rs = ppState.executeQuery();
            while(rs.next()){
                tableOrder.addRow(new Object[]{rs.getString("MADH"),
                rs.getString("MASP"),rs.getInt("SOLUONG"),
                rs.getInt("DONGIA"),rs.getInt("TONGTIEN"),
                rs.getString("DIACHIGIAOHANG"),rs.getDate("THOIGIANLAP"),
                rs.getInt("TINHTRANG")});
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(BranchPane, "SYS ERROR!!");
        }
    }//GEN-LAST:event_OrderNavButtonActionPerformed

    private void UpdateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateOrderButtonActionPerformed
        try{            
            if(jTableOrder.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No order is selected to update");
            }
            else{
                int[] selected = jTableOrder.getSelectedRows();
                for(int row: selected){
                    int statusUpdate = Integer.parseInt(tableOrder.getValueAt(row, 7).toString());
                    String updOrderQRY = "UPDATE DONHANG SET TINHTRANG = ?";               
                        PreparedStatement ppState = _connection.prepareStatement(updOrderQRY);
                        ppState.setInt(1,statusUpdate); //TENHS              
                        ppState.execute();
                        JOptionPane.showMessageDialog(rootPane,"Cập nhật thành công");
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateOrderButtonActionPerformed

    private void WatchDetailContractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatchDetailContractButtonActionPerformed
        int index = jTableContract.getSelectedRow();
        String ID = tableContract.getValueAt(index, 0).toString();
        ContractDetailForm dtailForm = new ContractDetailForm(ID);
        dtailForm.setVisible(true);
    }//GEN-LAST:event_WatchDetailContractButtonActionPerformed

    private void AccountButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountButton1ActionPerformed
        System.exit(0);
        //TODO: BACK TO LOGIN SCREEN
    }//GEN-LAST:event_AccountButton1ActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        AddProductForm addForm = new AddProductForm(partnerID);
        addForm.setVisible(true);
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void DeleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                String ID = tableProduct.getValueAt(row,0).toString();
                String dlProductQRY = "DELETE SANPHAM WHERE MASP = ?";               
                PreparedStatement ppState = _connection.prepareStatement(dlProductQRY);
                ppState.setString(1,ID);
                if(!ppState.execute()){
                    JOptionPane.showMessageDialog(rootPane,"DELETE SUCCESS");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"DELETE FAIL");
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteProductButtonActionPerformed

    private void inPriceFixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPriceFixButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                int amount = Integer.parseInt(AmountTextField.getText());
                if(!AmountTextField.getText().matches("[0-9]+")){
                    return;
                }
                String name = tableProduct.getValueAt(row,1).toString();
                String ID = tableProduct.getValueAt(row,0).toString();

                CallableStatement cstmt = _connection.prepareCall("{? = call TANG_GIA_SP_DOITAC_FIX(?, ? ,?)}");
                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.setString(2,partnerID);
                cstmt.setString(3,ID);
                cstmt.setInt(4,amount);
                if(cstmt.execute()){
                    int rs = cstmt.getInt(1);
                    if(rs ==1){
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE SUCCESS");
                    }
                    else{
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE FAIL");
                    }
                }
                else{
                    //JOptionPane.showMessageDialog(rootPane,"SYS ERROR");
                }
                cstmt.close();
                ReFresh();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_inPriceFixButtonActionPerformed

    private void BranchSupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchSupButtonActionPerformed
        int index = jTableProduct.getSelectedRow();
        if(index>=0){
            String pdID = tableProduct.getValueAt(index, 0).toString();
            BranchSupplyForm branchSupForm = new BranchSupplyForm(pdID);
            branchSupForm.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"No product is selected");
        }
    }//GEN-LAST:event_BranchSupButtonActionPerformed

    private void AccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountButtonActionPerformed

    private void CutPriceDLProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutPriceDLProductButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                int amount = Integer.parseInt(AmountTextField.getText());
                if(!AmountTextField.getText().matches("[0-9]+")){
                    return;
                }
                String name = tableProduct.getValueAt(row,1).toString();
                String ID = tableProduct.getValueAt(row,0).toString();
                //String updProductQRY = "UPDATE SANPHAM SET TENSP = ?, DONGIA = ?"
                //        + " WHERE MASP = ?";      
                String updProductQRY = "GIAM_GIA_SP_DOITAC_DL ?,?,?";
                
                CallableStatement cstmt = _connection.prepareCall("{? = call GIAM_GIA_SP_DOITAC_DL(?, ? ,?)}");
                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.setString(2,partnerID);
                cstmt.setString(3,ID);
                cstmt.setInt(4,amount);
                if(!cstmt.execute()){
                    int rs = cstmt.getInt(1);
                    if(rs ==1){
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE SUCCESS");
                    }
                    else{
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE FAIL");
                    }
                }
                else{
                    //JOptionPane.showMessageDialog(rootPane,"SYS ERROR");
                }
                cstmt.close();
                ReFresh();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_CutPriceDLProductButtonActionPerformed

    private void inPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPriceButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                int amount = Integer.parseInt(AmountTextField.getText());
                if(!AmountTextField.getText().matches("[0-9]+")){
                    return;
                }
                String name = tableProduct.getValueAt(row,1).toString();
                String ID = tableProduct.getValueAt(row,0).toString();    
                     
                CallableStatement cstmt = _connection.prepareCall("{? = call TANG_GIA_SP_DOITAC(?, ? ,?)}");
                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.setString(2,partnerID);
                cstmt.setString(3,ID);
                cstmt.setInt(4,amount);
                if(!cstmt.execute()){
                    int rs = cstmt.getInt(1);
                    if(rs ==1){
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE SUCCESS");
                    }
                    else{
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE FAIL");
                    }
                }
                else{
                    //JOptionPane.showMessageDialog(rootPane,"SYS ERROR");
                }
                cstmt.close();
                ReFresh();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_inPriceButtonActionPerformed

    private void CutPriceProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutPriceProductButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                int amount = Integer.parseInt(AmountTextField.getText());
                if(!AmountTextField.getText().matches("[0-9]+")){
                    return;
                }
                String name = tableProduct.getValueAt(row,1).toString();
                String ID = tableProduct.getValueAt(row,0).toString();
                
                CallableStatement cstmt = _connection.prepareCall("{? = call GIAM_GIA_SP_DOITAC(?, ? ,?)}");
                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.setString(2,partnerID);
                cstmt.setString(3,ID);
                cstmt.setInt(4,amount);
                if(!cstmt.execute()){
                    int rs = cstmt.getInt(1);
                    if(rs ==1){
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE SUCCESS");
                    }
                    else{
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE FAIL");
                    }
                }
                else{
                   // JOptionPane.showMessageDialog(rootPane,"SYS ERROR");
                }
                cstmt.close();
                ReFresh();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_CutPriceProductButtonActionPerformed

    private void inPriceDLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPriceDLButtonActionPerformed
        try{            
            if(jTableProduct.getSelectedRow()<0){
                JOptionPane.showMessageDialog(rootPane, "No product is selected to update");
            }
            else{
                int row = jTableProduct.getSelectedRow();
                int amount = Integer.parseInt(AmountTextField.getText());
                if(!AmountTextField.getText().matches("[0-9]+")){
                    return;
                }
                String name = tableProduct.getValueAt(row,1).toString();
                String ID = tableProduct.getValueAt(row,0).toString();

                CallableStatement cstmt = _connection.prepareCall("{? = call TANG_GIA_SP_DOITAC_DL(?, ? ,?)}");
                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.setString(2,partnerID);
                cstmt.setString(3,ID);
                cstmt.setInt(4,amount);
                if(!cstmt.execute()){
                    int rs = cstmt.getInt(1);
                    if(rs ==1){
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE SUCCESS");
                    }
                    else{
                        //JOptionPane.showMessageDialog(rootPane,"UPDATE FAIL");
                    }
                }
                cstmt.close();
                ReFresh();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_inPriceDLButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPartnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPartnerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountButton;
    private javax.swing.JButton AccountButton1;
    private javax.swing.JButton AddProductButton;
    private javax.swing.JTextField AmountTextField;
    private javax.swing.JButton BranchNavButton;
    private javax.swing.JPanel BranchPane;
    private javax.swing.JButton BranchSupButton;
    private javax.swing.JButton ContractNavButton;
    private javax.swing.JPanel ContractPane;
    private javax.swing.JButton CutPriceDLProductButton;
    private javax.swing.JButton CutPriceProductButton;
    private javax.swing.JButton DeleteProductButton;
    private javax.swing.JButton OrderNavButton;
    private javax.swing.JPanel OrderPane;
    private javax.swing.JButton ProductNavButton;
    private javax.swing.JPanel ProductPane;
    private javax.swing.JButton UpdateOrderButton;
    private javax.swing.JButton WatchDetailContractButton;
    private javax.swing.JButton inPriceButton;
    private javax.swing.JButton inPriceDLButton;
    private javax.swing.JButton inPriceFixButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBranch;
    private javax.swing.JTable jTableContract;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
