--TRAN 1
USE QLDonHang
SELECT* FROM SANPHAM
DECLARE @RT INT
EXEC @RT = SUA_GIA_DOITAC 'TK00003','SP97',10000
IF @RT = 0
	PRINT N'SỬA GIÁ THẤT BẠI'
ELSE
	PRINT N'SỬA GIÁ THÀNH CÔNG'
SELECT* FROM SANPHAM