--TRAN 2
USE QLDonHang
SELECT* FROM SANPHAM
DECLARE @RT INT
EXEC @RT = SUA_SP_DOITAC 'TK00003','SP97','Robot trái cây',150000
IF @RT = 0
	PRINT N'SỬA SẢN PHẨM THẤT BẠI'
ELSE
	PRINT N'SỬA SẢN PHẨM THÀNH CÔNG'
SELECT* FROM SANPHAM