USE QLDonHang
GO
CREATE
or ALTER
PROC SUA_GIA_DOITAC_FIX
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@DonGia INT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @DONGIA < 0
	BEGIN
		PRINT N'GIÁ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	WAITFOR DELAY '0:0:10'
-----------------
	UPDATE SANPHAM
	SET DONGIA = @DONGIA
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1


GO
CREATE
or ALTER
PROC SUA_SP_DOITAC_FIX
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@TenSP NVARCHAR(20),
	@GiaSP INT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
		IF @GiaSP < 0
	BEGIN
		PRINT N'GIÁ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
-----------------
	UPDATE SANPHAM
	SET DONGIA = @GiaSP,
		TenSP = @TenSP
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1