USE QLDonHang
GO
CREATE
or ALTER
PROC TANG_GIA_SP_DOITAC
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@ThayDoi INT
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	DECLARE @GiaSP INT = (SELECT DONGIA FROM SANPHAM WHERE MASP = @MaSP)

	IF @ThayDoi < 0
	BEGIN
		PRINT N'GIÁ TRỊ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	WAITFOR DELAY '0:0:5'
-----------------
	UPDATE SANPHAM
	SET DONGIA = @GiaSP+@ThayDoi
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1


GO
CREATE
or ALTER
PROC GIAM_GIA_SP_DOITAC
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@ThayDoi INT
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
		
	DECLARE @GiaSP INT = (SELECT DONGIA FROM SANPHAM WHERE MASP = @MaSP)

	IF @ThayDoi < 0
	BEGIN
		PRINT N'GIÁ TRỊ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	IF @GiaSP - @ThayDoi < 0
	BEGIN
		PRINT N'THAY ĐỔI KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END


-----------------
	UPDATE SANPHAM
	SET DONGIA = @GiaSP-@ThayDoi
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1