--TRAN 2
USE QLDonHang
DECLARE @RT INT
EXEC @RT = SUA_SP_DOITAC_FIX 'TK0003','SP08','Robot trái cây',150000
IF @RT = 0
	PRINT N'SỬA SẢN PHẨM THẤT BẠI'
ELSE
	PRINT N'SỬA SẢN PHẨM THÀNH CÔNG'
SELECT* FROM SANPHAM