----------Phantom---------- 
GO
CREATE
--đối tác thực hiện thay đổi mật khẩu tài khoản
PROC USP_CAU13_DT  
	@MaDT CHAR(10),
	@MKHienTai VARCHAR(10),
	@MKMoi VARCHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
	
	IF NOT EXISTS (SELECT* FROM TAIKHOAN WHERE MATK = @MADT)
	BEGIN
		PRINT N'DỮ LIỆU KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END

	IF NOT EXISTS (SELECT* FROM TAIKHOAN WHERE MATK = @MADT AND MATKHAU = @MKHienTai)
	BEGIN
		PRINT N'SAI MẬT KHẨU'
		ROLLBACK TRAN
		RETURN 0
	END


-------ĐỂ TEST----
	WAITFOR DELAY '0:0:10'
	UPDATE TAIKHOAN
	SET MATKHAU = @MKMoi
	WHERE MATK = @MaDT
	
	IF NOT EXISTS (SELECT* FROM TAIKHOAN WHERE MATK = @MADT)
	BEGIN
		PRINT N'TÀI KHOẢN ĐÃ BỊ XÓA'
		ROLLBACK TRAN
		RETURN 0
	END

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1

---
GO
CREATE

--quản trị viên thực hiện xóa tài khoản của đối tác
PROC USP_CAU13_QTV
	@MADT CHAR(10)
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM TAIKHOAN WHERE MaTK = @MaDT)
	BEGIN
		PRINT N'KHÔNG CÓ DỮ LIỆU TRONG HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END


	DELETE TAIKHOAN
	WHERE MATK = @MADT
	END TRY	

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0	
	END CATCH
COMMIT TRAN
RETURN 1