USE QLDonHang
GO
CREATE OR ALTER	
PROC USP_CAU6_TX --CẬP NHẬT TÌNH TRẠNG ĐƠN HÀNG - TÀI XẾ
	@madonhang 	CHAR(20),
	@matx 		CHAR(10),
	@tinhtrang 	INT
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM TAIXE WHERE MATX = @matx)
	BEGIN
		PRINT N'TÀI XẾ KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM DONHANG WHERE MADH = @madonhang)
	BEGIN
		PRINT N'ĐƠN HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM DONHANG WHERE MATX = @matx AND MADH = @madonhang)
	BEGIN
		PRINT N'TÀI XẾ KHÔNG CÓ ĐƠN HÀNG TRÊN'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @tinhtrang > 3 OR @tinhtrang <= 0 OR
	@tinhtrang <= (SELECT TINHTRANG FROM DONHANG WHERE MATX = @matx AND MADH= @madonhang)
	BEGIN
		PRINT N'CẬP NHẬT TÌNH TRẠNG KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	UPDATE DONHANG
	SET TINHTRANG = @tinhtrang
	WHERE MATX = @matx AND MADH = @madonhang

	SELECT TINHTRANG 
	FROM DONHANG 
	WHERE MATX = @matx AND MADH = @madonhang
	---------------------
	WAITFOR DELAY '0:0:05'
	ROLLBACK TRAN
	RETURN 0
	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO
CREATE OR ALTER
PROC USP_CAU6_KH --KIỂM TRA TÌNH TRẠNG ĐƠN HÀNG - KHÁCH HÀNG
	@madonhang 	CHAR(20),
	@makh 		CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM KHACHHANG WHERE MAKH = @makh)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM DONHANG WHERE MADH = @madonhang)
	BEGIN
		PRINT N'ĐƠN HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM DONHANG WHERE MAKH = @makh AND MADH = @madonhang)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG CÓ ĐƠN HÀNG TRÊN'
		ROLLBACK TRAN
		RETURN 0
	END
-----------------
	SELECT TINHTRANG 
	FROM DONHANG 
	WHERE MAKH = @makh AND MADH = @madonhang

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
	