USE QLDonHang
GO
CREATE or ALTER
PROC SUA_GIA_DOITAC1
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@DonGia INT
AS
BEGIN TRAN
	WAITFOR DELAY '0:0:05'
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
	IF @DONGIA < 0
	BEGIN
		PRINT N'GIÁ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
-----------------
	BEGIN TRY
	UPDATE SANPHAM
	SET DONGIA = @DONGIA
	WHERE MASP = @MASP
	END TRY

	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'GIÁ MỚI : ' + CAST(@DONGIA AS VARCHAR(20))
	PRINT N'SỬA GIÁ THÀNH CÔNG'
COMMIT TRAN

GO
CREATE or ALTER
PROC SUA_GIA_DOITAC2_DL
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@DONGIA INT
AS
BEGIN TRAN
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
		IF @DONGIA < 0
	BEGIN
		PRINT N'GIÁ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
-----------------
	WAITFOR DELAY '0:0:05'
	BEGIN TRY
	UPDATE SANPHAM
	SET DONGIA = @DONGIA
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'GIÁ MỚI : ' + CAST(@DONGIA AS VARCHAR(20))
	PRINT N'SỬA GIÁ THÀNH CÔNG'
COMMIT TRAN