USE QLDonHang
GO
CREATE
or ALTER
PROC TANG_GIA_SP_DOITAC_DL
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@ThayDoi INT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	WAITFOR DELAY '0:0:5'
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	DECLARE @GiaSP INT = (SELECT DONGIA FROM SANPHAM WHERE MASP = @MaSP)

	IF @ThayDoi < 0
	BEGIN
		PRINT N'GIÁ TRỊ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
-----------------
	UPDATE SANPHAM
	SET DONGIA = @GiaSP+@ThayDoi
	WHERE MASP = @MASP
	
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
RETURN 1


GO
CREATE
or ALTER
PROC GIAM_GIA_SP_DOITAC_DL
	@MaDT CHAR(10),
	@MaSP CHAR(15),
	@ThayDoi INT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT* FROM DOITAC WHERE MaDT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS (SELECT* FROM SANPHAM WHERE MaSP = @MASP)
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END
		
	DECLARE @GiaSP INT = (SELECT DONGIA FROM SANPHAM WHERE MASP = @MaSP)

	IF @ThayDoi < 0
	BEGIN
		PRINT N'GIÁ TRỊ KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	IF @GiaSP - @ThayDoi < 0
	BEGIN
		PRINT N'THAY ĐỔI KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN 0
	END

	WAITFOR DELAY '0:0:10'
	
-----------------
	UPDATE SANPHAM
	SET DONGIA = @GiaSP-@ThayDoi
	WHERE MASP = @MASP
	

	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
RETURN 1